# Ultra-minimal config for speed testing
model:
  unet:
    sample_size: 128  # Very small for speed
    in_channels: 4
    out_channels: 4
    layers_per_block: 1  # Minimal depth
    block_out_channels: [64, 64, 128, 128]  # Very small
    down_block_types:
      - "CrossAttnDownBlock2D"
      - "DownBlock2D"
    up_block_types:
      - "UpBlock2D" 
      - "CrossAttnUpBlock2D"
    cross_attention_dim: 768
    attention_head_dim: 8
    use_linear_projection: true

diffusion:
  num_train_timesteps: 1000
  beta_schedule: "scaled_linear"
  prediction_type: "epsilon"
  clip_sample: false

training:
  learning_rate: 1e-4
  weight_decay: 0.01
  epsilon: 1e-8
  optimizer: "adamw"
  max_train_steps: 10  # Just 10 steps for testing!
  batch_size: 1
  gradient_accumulation_steps: 1  # No accumulation for speed
  mixed_precision: "fp16"
  gradient_clipping: 1.0
  use_ema: false
  ema_decay: 0.9999

data:
  dataset_name: "coco"
  dataset_type: "coco"
  image_size: 128  # Very small for speed
  limit_dataset_size: 10  # Only 10 images!
  download_coco: true
  batch_size: 1

logging:
  log_interval: 1  # Log every step
  save_interval: 100
  project_name: "scribble-diffusion-debug"
  run_name: "speed-test"

validation:
  validation_steps: 50
  num_validation_images: 1
  guidance_scale: 7.5
  num_inference_steps: 20