# Optimal ScribbleDiffusion Training Configuration
# Fixed model saving + optimal 256x256 dimensions + focused dataset

model:
  unet:
    in_channels: 4
    out_channels: 4
    model_channels: 320
    use_linear_projection: false  # Use conv projections for compatibility
  
  sketch_encoder:
    in_channels: 1
    hidden_dim: 256
    num_sketch_tokens: 77
    cross_attention_dim: 768
  
  vae:
    model_name: "runwayml/stable-diffusion-v1-5"
    subfolder: "vae"
  
  text_encoder:
    model_name: "runwayml/stable-diffusion-v1-5"
    subfolder: "text_encoder"

data:
  dataset_type: "focused"  # Use focused dataset instead of COCO
  dataset_path: "data/apple_dataset"  # Path to focused dataset
  image_size: 256  # OPTIMAL: Good quality, manageable memory
  sketch_size: 256  # Match image size
  batch_size: 8    # Can increase with 256x256
  max_sequence_length: 77
  
training:
  max_train_steps: 2000  # Much faster with focused dataset
  learning_rate: 1e-4
  batch_size: 8
  gradient_accumulation_steps: 2  # Effective batch size = 16
  gradient_checkpointing: true
  mixed_precision: "fp16"  # Enable on better hardware
  
  # Optimizer settings
  optimizer: "adamw"
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.01
  epsilon: 1e-8
  
  # Learning rate schedule
  lr_scheduler: "cosine"
  num_warmup_steps: 100
  
  # Regularization (less aggressive for focused dataset)
  text_drop_prob: 0.1
  sketch_drop_prob: 0.1
  
  # EMA
  use_ema: true
  ema_decay: 0.999

diffusion:
  num_train_timesteps: 1000
  beta_schedule: "linear"
  prediction_type: "epsilon"
  clip_sample: false

logging:
  project_name: "scribble-diffusion-focused"
  run_name: "apple-256x256"
  log_interval: 50
  save_interval: 200  # Save every 200 steps (10% of training)
  log_with: ["tensorboard"]

validation:
  validation_steps: 200
  num_validation_images: 4
  validation_prompts:
    - "a red apple"
    - "a green apple" 
    - "a yellow apple"
    - "an apple with stem"

paths:
  output_dir: "outputs/apple_focused"
  cache_dir: "cache"
  logging_dir: "logs"