# Validation-only configuration for ScribbleDiffusion
# Uses pretrained SD 1.5 components with zero-initialized HintEncoder
model:
  # U-Net Architecture - Standard SD 1.5 for pretrained compatibility
  unet:
    model_name: "runwayml/stable-diffusion-v1-5"
    subfolder: "unet"
    
  # Sketch Conditioning (ControlNet-lite) - Will be zero-initialized
  hint_encoder:
    in_channels: 1  # Binary edge map
    hint_channels: [16, 32, 96, 256]  # Standard ControlNet proportions
    injection_layers: [0, 1, 2, 3]  # Inject at all scales
    injection_method: "add"  # "add" or "film"
    
  # Pretrained Components (frozen)
  vae:
    model_name: "runwayml/stable-diffusion-v1-5"
    subfolder: "vae"
    
  text_encoder:
    model_name: "runwayml/stable-diffusion-v1-5"
    subfolder: "text_encoder"
    max_length: 77

# Diffusion Settings
diffusion:
  num_train_timesteps: 1000
  beta_schedule: "linear"
  prediction_type: "epsilon"
  clip_sample: false
  
# Validation Configuration (no training)
validation:
  num_validation_images: 4  # Small for testing
  guidance_scale_text: 7.5
  guidance_scale_sketch: 1.5  # Low since HintEncoder is zero-initialized
  num_inference_steps: 20  # Faster for testing

# Data for validation
data:
  image_size: 512  # Standard SD resolution
  edge_method: canny
  canny_low: 50
  canny_high: 150

# Output paths
paths:
  output_dir: ./outputs/validation
  cache_dir: ./cache
